name: Github actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  Manual-Deployment-Job:
    runs-on: ubuntu-latest

    steps:
      - name: github repository source pull
        uses: actions/checkout@v4

      - name: jdk 17 install
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: applicaton.yml 생성
        run: echo ${{secrets.APPLICATION2_YML}} > ./src/main/resources/application.yml

      - name: test and build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --warning-mode all
          ./gradlew test --scan


      - name: jar file name edit
        run: mv ./build/libs/*SNAPSHOT.jar ./app.jar

#      - name: send jar file to ec2
#      - name: SSH로 ec2 access